### ISSUE TITLE
fluppy compile error

### ISSUE THREAD

**Issue by sunkechenjing** [PocketSprite/8bkc-fluppy#1]
make[2]: Entering directory '/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile'
cc -o conv_png_tile -lm -lxml2 -lgd main.o
main.o：在函数‘findNodeByName’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:45：对‘xmlStrcmp’未定义的引用
main.o：在函数‘output_tileset’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:54：对‘gdImageCreateFromPng’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:78：对‘gdImageGetTrueColorPixel’未定义的引用
main.o：在函数‘load_tileset’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:105：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:109：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:110：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:111：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:125：对‘xmlGetProp’未定义的引用
main.o:/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:137: 跟着更多未定义的参考到 xmlGetProp
main.o：在函数‘load_tileset’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:160：对‘xmlStrcmp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:161：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:169：对‘xmlStrcmp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:170：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:180：对‘xmlStrcmp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:181：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:182：对‘xmlGetProp’未定义的引用
main.o：在函数‘load_tileset_ext’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:235：对‘xmlReadFile’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:240：对‘xmlDocGetRootElement’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:246：对‘xmlFreeDoc’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:252：对‘xmlFreeDoc’未定义的引用
main.o：在函数‘write_map’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:257：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:258：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:259：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:280：对‘xmlGetProp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:285：对‘xmlNodeListGetString’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:302：对‘xmlFree’未定义的引用
main.o：在函数‘parse_tmx_file’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:338：对‘xmlReadFile’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:340：对‘xmlDocGetRootElement’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:345：对‘xmlStrcmp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:361：对‘xmlStrcmp’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:369：对‘xmlFreeDoc’未定义的引用
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:375：对‘xmlFreeDoc’未定义的引用
main.o：在函数‘main’中：
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/main.c:407：对‘xmlCleanupParser’未定义的引用
collect2: error: ld returned 1 exit status
Makefile:7: recipe for target 'conv_png_tile' failed
make[2]: *** [conv_png_tile] Error 1
make[2]: Leaving directory '/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile'
/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/Makefile.componentbuild:5: recipe for target '/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/conv_png_tile' failed
make[1]: *** [/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile/conv_png_tile] Error 2
/home/sun/esp/esp-idf/make/project.mk:450: recipe for target 'component-main-build' failed
make: *** [component-main-build] Error 2

**Comment by Spritetm** [comment]
Hmm, sounds like an linker order issue. Can you try

```
cd home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile
cc -o conv_png_tile main.o -lm -lxml2 -lgd
```
and post the output of that command?

**Comment by sunkechenjing** [comment]
root@sun-Latitude-E7270:/home/sun/esp/8bkc-fluppy# cd home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile cc -o conv_png_tile main.o -lm -lxml2 -lgd
bash: cd: too much parameter
 
is this command error!

**Comment by sunkechenjing** [comment]
After executeing the command,there isn't any output.

root@sun-Latitude-E7270:/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile# cc -o conv_png_tile main.o -lm -lxml2 -lgd
root@sun-Latitude-E7270:/home/sun/esp/8bkc-sdk/8bkc-components/tilegfx/conv_png_tile#

**Comment by Spritetm** [comment]
Sounds like I made a mistake in the order of commands. If anything, with the lines above, you manually compiled the tool; if you re-try running make, it should now succeed; can you try that?

If any, I'll push a fix for this on my end so no one else gets caught with this.

**Comment by sunkechenjing** [comment]
Thanks!  after using cc compile conv_png_tile,compile is succeed

**Comment by sunkechenjing** [comment]
Thanks! After using cc compile conv_png_tile,compile is succeed.

**Comment by Spritetm** [comment]
Awesome! Closing this then. Underlying issue is fixed in commit 8a9119f  .

**Comment by sunkechenjing** [comment]
what 's the 8a9119f

**Comment by Spritetm** [comment]
Ah, that's a commit in the 8bkc-sdk branch.
