### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by sunkechenjing** [PocketSprite/8bkc-fluppy#2]
ets Jun  8 2016 00:22:57

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0028,len:4
load:0x3fff002c,len:7156
load:0x40078000,len:0
load:0x40078000,len:16520
entry 0x40079278
[0;32mI (28) boot: ESP-IDF v3.1-dev-541-g7e2028d5-dirty 2nd stage bootloader[0m
[0;32mI (28) boot: compile time 21:16:38[0m
[0;32mI (29) boot: Enabling RNG early entropy source...[0m
[0;32mI (34) qio_mode: Enabling default flash chip QIO[0m
[0;32mI (40) boot: SPI Speed      : 40MHz[0m
[0;32mI (44) boot: SPI Mode       : QIO[0m
[0;32mI (48) boot: SPI Flash Size : 4MB[0m
[0;32mI (52) boot: Partition Table:[0m
[0;32mI (55) boot: ## Label            Usage          Type ST Offset   Length[0m
[0;32mI (63) boot:  0 appfs            AppFs            43 03 00010000 00070000[0m
[0;32mI (70) boot:  1 nvs              WiFi data        01 02 00080000 00010000[0m
[0;32mI (78) boot:  2 chooser          factory app      00 00 00090000 00360000[0m
[0;32mI (85) boot:  3 coredump         Unknown data     01 03 003f0000 00010000[0m
[0;32mI (93) boot: End of partition table[0m
[0;32mI (97) boot: AppFs found[0m
[0;32mI (100) appfs: Meta page 0: invalid (serial 0)[0m
[0;32mI (105) appfs: Meta page 1: invalid (serial 0)[0m
[0;32mI (110) appfs: No valid page found.[0m
[0;31mE (114) appfs: No valid meta info found. Bailing out.[0m
[0;31mE (120) boot: AppFs initialization failed[0m
[0;32mI (125) boot: Disabling RNG early entropy source...[0m
[0;32mI (130) boot: Loading app partition at offset 00090000[0m
[0;32mI (136) esp_image: segment 0: paddr=0x00090020 vaddr=0x3f400020 size=0x19358 (103256) map[0m
[0;32mI (175) esp_image: segment 1: paddr=0x000a9380 vaddr=0x3ffb0000 size=0x01f20 (  7968) load[0m
[0;32mI (178) esp_image: segment 2: paddr=0x000ab2a8 vaddr=0x40080000 size=0x00400 (  1024) load[0m
[0;32mI (183) esp_image: segment 3: paddr=0x000ab6b0 vaddr=0x40080400 size=0x04960 ( 18784) load[0m
[0;32mI (198) esp_image: segment 4: paddr=0x000b0018 vaddr=0x400d0018 size=0x143b4 ( 82868) map[0m
[0;32mI (224) esp_image: segment 5: paddr=0x000c43d4 vaddr=0x40084d60 size=0x0397c ( 14716) load[0m
[0;32mI (230) esp_image: segment 6: paddr=0x000c7d58 vaddr=0x400c0000 size=0x00000 (     0) load[0m
NVS inited
Opening NVS storage for app MyApp
Using serial port for input.
Use arrow keys or JIKL for D-pad.
Use A, S for A, B buttons.
Use Z for start, X for select, P for power.
Sndmixer task up.

**Comment by Spritetm** [comment]
....sooo... where is the error?

**Comment by sunkechenjing** [comment]
I flash fluppy to esp32. My mcu isn't reboot through  serial debug info.  My lcd is st7735s. It have 6 contorl por : CS RST RS SDA SCL LED. Is this spi interface?  can it show fluppy?

**Comment by Spritetm** [comment]
That should work (although I haven't been able to test it myself). You need to configure the LCD to the right pins, however. Run 'make menuconfig' and under 'PocketSprite hardware config', select 'Custom Hardware', the ST7735s LCD and make sure the GPIOs where your LCD is connected are configured correctly.

**Comment by Spritetm** [comment]
Closing; if this is still an issue, feel free to reopen.
