### ISSUE TITLE
Can't make

### ISSUE THREAD

**Issue by ishotjr** [PocketSprite/8bkc-fluppy#3]
Hi, I completed the required environment setup [per the docs](http://pocketsprite-sdk.readthedocs.io/en/latest/gettingstarted/index.html) and can build for [ESP-IDF](https://github.com/espressif/esp-idf) successfully, but when I try to `make` a fresh clone of this repo, I get:

```bash
In file included from /home/ishotjr/esp/esp-idf/components/esp32/include/rom/ets_sys.h:21:0,
                 from /home/ishotjr/esp/esp-idf/components/log/include/esp_log.h:21,
                 from /home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:17:
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c: In function 'enable_qio_mode':
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: error: 'EFUSE_RD_CHIP_VER_RESERVE_S' undeclared (first use in this function)
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:32: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                ^
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: note: each undeclared identifier is reported only once for each function it appears in
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:32: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                ^
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: error: 'EFUSE_RD_CHIP_VER_RESERVE_V' undeclared (first use in this function)
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:44: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                            ^
/home/ishotjr/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'flash_qio_mode.o' failed
make[2]: *** [flash_qio_mode.o] Error 1
/home/ishotjr/esp/esp-idf/make/project.mk:467: recipe for target 'component-main-build' failed
make[1]: *** [component-main-build] Error 2
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/Makefile.projbuild:40: recipe for target '/mnt/c/Dev/8bkc-fluppy/build/bootloader/bootloader.bin' failed
make: *** [/mnt/c/Dev/8bkc-fluppy/build/bootloader/bootloader.bin] Error 2
```

Any ideas?  I accepted the defaults for the questions presented during build.  Thanks!! :bowtie: ❤️

**Comment by Spritetm** [comment]
You are running master esp-idf I presume? (As in, you didn't check out a specific version like v2.1 or v3.0?)

**Comment by ishotjr** [comment]
@Spritetm yep - oops - was I supposed to use a specific version? 😅

**Comment by Spritetm** [comment]
No, just checked - both 3.0 and master compile fine for me. Weird. I'll investigate further.

**Comment by ishotjr** [comment]
@Spritetm thank you! It's highly likely that I'm doing something wrong - I just got my PocketSprite today, set up the dev env. and attempted to make this example... 😊 

Below is the entirety of what I did if that helps; note that this is on [WSL](https://msdn.microsoft.com/commandline/wsl/about) - hopefully that's not a problem?  Thanks! :bowtie: ❤️ 

---

```bash
sudo apt update
sudo apt install gcc git wget make libncurses-dev flex bison gperf python python-serial
cd ~
wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
mkdir -p ~/esp
cd ~/esp
tar -xzf ~/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
nano ~/.bash_aliases
```

Added to `.bash_aliases`:  

```bash
alias get_esp32='export PATH="$PATH:$HOME/esp/xtensa-esp32-elf/bin"'
```

Tested:  

```bash
get_esp32
printenv PATH
```

Cloned [ESP-IDF](https://github.com/espressif/esp-idf):  

```bash
cd ~/esp
git clone --recursive https://github.com/espressif/esp-idf.git
```

Added to `.bash_aliases`:  

```bash
export IDF_PATH=~/esp/esp-idf
```

```
cd ~/esp
cp -r $IDF_PATH/examples/get-started/hello_world .
cd ~/esp/hello_world
make menuconfig
make
```

WORKS!! :rocket:  


Cloned [PocketSprite SDK](https://github.com/PocketSprite/8bkc-sdk):  

```bash
cd ~/esp
git clone --recursive https://github.com/PocketSprite/8bkc-sdk.git
```


Added to `.bash_aliases`:  

```bash
export POCKETSPRITE_PATH=~/esp/8bkc-sdk
```

Final check:  

```bash
get_esp32
printenv PATH
printenv IDF_PATH
printenv POCKETSPRITE_PATH
```


```
sudo apt install gcc libgd-dev libxml2-dev
```


Cloned and built [Fluppy Bird](https://github.com/PocketSprite/8bkc-fluppy):  

```bash
cd /mnt/c/Dev
git clone git@github.com:PocketSprite/8bkc-fluppy.git
cd /mnt/c/Dev/8bkc-fluppy
make
```

Failed:  

```bash
In file included from /home/ishotjr/esp/esp-idf/components/esp32/include/rom/ets_sys.h:21:0,
                 from /home/ishotjr/esp/esp-idf/components/log/include/esp_log.h:21,
                 from /home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:17:
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c: In function 'enable_qio_mode':
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: error: 'EFUSE_RD_CHIP_VER_RESERVE_S' undeclared (first use in this function)
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:32: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                ^
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: note: each undeclared identifier is reported only once for each function it appears in
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:32: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                ^
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/subproject/main/flash_qio_mode.c:186:66: error: 'EFUSE_RD_CHIP_VER_RESERVE_V' undeclared (first use in this function)
         uint32_t chip_ver = REG_GET_FIELD(EFUSE_BLK0_RDATA3_REG, EFUSE_RD_CHIP_VER_RESERVE);
                                                                  ^
/home/ishotjr/esp/esp-idf/components/soc/esp32/include/soc/soc.h:189:44: note: in definition of macro 'REG_GET_FIELD'
             ((REG_READ(_r) >> (_f##_S)) & (_f##_V));
                                            ^
/home/ishotjr/esp/esp-idf/make/component_wrapper.mk:285: recipe for target 'flash_qio_mode.o' failed
make[2]: *** [flash_qio_mode.o] Error 1
/home/ishotjr/esp/esp-idf/make/project.mk:467: recipe for target 'component-main-build' failed
make[1]: *** [component-main-build] Error 2
/home/ishotjr/esp/8bkc-sdk/8bkc-components/bootloader/Makefile.projbuild:40: recipe for target '/mnt/c/Dev/8bkc-fluppy/build/bootloader/bootloader.bin' failed
make: *** [/mnt/c/Dev/8bkc-fluppy/build/bootloader/bootloader.bin] Error 2
```

**Comment by Spritetm** [comment]
Okay, I just did a fair amount of commits to fix the PocketSprite SDK to the just-released 3.0 release of ESP-IDF. Can you try the following:

- In the 8bkc-sdk, do ``git pull`` followed by ``git submodule update --recursive``
- In the 8bkc-fluppy dir, do ``git pull``
- Retry building Fluppy Bird

to see if it compiles now?
Note that the resulting binary will have some color glitches. That seems to have stemmed from a merge artifact in 8bkc-sdk: the tile engine does something derpy now when downscaling colors. I'll fix that next.

**Comment by ishotjr** [comment]
@Spritetm wow, I was surprised when you replied so quickly, but I'm absolutely stunned by your commitment to getting this working - thank you so much for the amazing turnaround on these fixes!  I feel like we're getting close, but I am now getting the following when I attempt to `make`:

```bash
make[1]: convert: Command not found
/home/ishotjr/esp/8bkc-sdk/8bkc-components/powerbtn_menu/component.mk:16: recipe for target 'graphics.inc' failed
make[1]: *** [graphics.inc] Error 127
/home/ishotjr/esp/8bkc-sdk/esp-idf/make/project.mk:450: recipe for target 'component-powerbtn_menu-build' failed
make: *** [component-powerbtn_menu-build] Error 2
```

Sounds like I just need `ImageMagick` maybe?  Will give that a try - and again, thanks so much!! 😍 👍

**Comment by ishotjr** [comment]
@Spritetm yep, clean build after installing `ImageMagick`! 🚀 🚀 🚀 

Sorry to ask, but...how do I install/run the binary on the PocketSprite?  The mUSB is power-only, right, so I can't flash from the CLI?  Can I use the same Wi-Fi upload as for ROMs?  Do I need to rename the file for it to be recognized or anything like that? (I noticed the other apps are `.app` for example)  Thanks!! :bowtie: ❤️

**Comment by ishotjr** [comment]
@Spritetm all up and running on the PocketSprite now - woohoo!! 🤘 :bowtie: 🤘 

Do you mind if I ask here: is there a preferable workflow vs. `make` / rename / switch Wi-Fi / upload - e.g. local emulation on the dev machine for example in order to increase speed of development?  No worries if not, I'm just curious - what you've accomplished here is marvelous! 😍  I hope to honor your commitment by entering the challenge - thanks again, so much!! 🏆

**Comment by Spritetm** [comment]
The workflow thing is something I'm still pondering on. For my own development, I have a pretty comfortable workflow, but it involves opening the PocketSprite and connecting an usb-to-serial converter (in my case: a hacked ESP8266 board so I also get automatic reset and bootloader action) to work. I can imagine not everyone wants to open their nice PocketSprite to solder a serial interface to it, however... so I've been thinking of a better workflow. In theory, one could modify the Chooser (the thing that allows you to pick a .app file) to connect to your local WiFi and automatically grab an app from a webserver, or accept an app that is uploaded using curl; that could also help retrieving serial logs (when redirected to a file on the filesystem) and crashdumps. This all is still pie-in-the-sky stuff, however, and I wouldn't mind the community helping me out a bit on that.

**Comment by ishotjr** [comment]
@Spritetm cool - thanks for answering my question; so would you recommend a Hacker Edition as a basis for this setup, or a homebrew ESP32+LCD or ESP-WROVER-KIT [as mentioned in the docs](http://pocketsprite-sdk.readthedocs.io/en/latest/hardware/fake.html)?  I like the hacked Chooser idea too!  What about emulation?  If not for the precise PocketSprite hardware, then perhaps just for the SDK itself?  I'm interested in helping if you can provide some direction... 😅

**Comment by Spritetm** [comment]
All are options with their own pros and cons. The homebrew ESP32+LCD/Wrover-Kit are nice options because you can debug your game/app logic in depth, if needed with a JTAG connection. The Hacker Edition is nice if you're doing stuff that is close to the hardware (changing HAL components) or doing appfs-related stuff (as the 'fake' pocketsprite doesn't have that). Emulation could be done in one of two ways: either by making a native version of the SDK (which may be somewhat painful, as ESP-IDF isn't really capable of building for multiple targets at the moment) or by taking an Xtensa version of QEmu and modelling the PocketSprite hardware in it.

I'm kind-of partial to the last option at the moment, as the state of qemu seems to be good enough to run most of the PocketSprite things and it would allow for running in a way that's very similar to the native run method, but with options to attach a debugger like you would do with JTAG.

**Comment by ishotjr** [comment]
Cool, I'd just started researching ESP32 emulation w/ QEMU - that would be ideal; I'll take a look at the [Xtensa docs](http://docs.zephyrproject.org/boards/xtensa/esp32/doc/esp32.html) - thanks! :bowtie:

**Comment by Spritetm** [comment]
Closing this as the original issue is resolved.
