### ISSUE TITLE
Compilation terminates with '8bkc-hal.h: No such file or directory'

### ISSUE THREAD

**Issue by classilla** [PocketSprite/8bkc-fluppy#5]
With revision `23399da6154b1958e4aebad49aa2953f4d83f5c6` and SDK revision `9477cf7d81af8afdb12136a3b20024b7ce502738`

```
macbookair(3):/Users/spectre/esp/8bkc-fluppy/% make
/Users/spectre/esp/8bkc-fluppy/main/component.mk:13: warning: undefined variable `ConvertTiles'
CC build/main/app_main.o
/Users/spectre/esp/8bkc-fluppy/main/app_main.c:4:69: fatal error: 8bkc-hal.h: No such file or directory
compilation terminated.
make[1]: *** [app_main.o] Error 1
make: *** [component-main-build] Error 2
macbookair(3):/Users/spectre/esp/8bkc-fluppy/% echo $IDF_PATH
/Users/spectre/esp/esp-idf
macbookair(3):/Users/spectre/esp/8bkc-fluppy/% echo $POCKETSPRITE_PATH
/Users/spectre/esp
macbookair(3):/Users/spectre/esp/8bkc-fluppy/% find $POCKETSPRITE_PATH -name 8bkc-hal.h -print
/Users/spectre/esp/8bkc-sdk/8bkc-components/8bkc-hal/include/8bkc-hal.h
```

The remainder of the SDK does build. I don't see a place to add include directories. What's the best fix?

**Comment by Spritetm** [comment]
You're supposed to set POCKETSPRITE_PATH to the directory of the SDK, in your case /Users/spectre/esp/8bkc-sdk .

**Comment by classilla** [comment]
Thanks, I don't know how I missed that. Two more questions:

- Where in the SDK does it say which file to upload to the PS? I looked at what was in the `build` directory and guessed `fluppy.bin`, renamed it to `fluppy.app` and uploaded that over WiFi, and it worked, but I couldn't find where that was documented. Is it always that?

- I also couldn't find if there is a way to upload over USB.

This was done on a Mac with 10.12, so the SDK seems to work fine on macOS (libxml2 needed a little coercion but that's not this project's bug).

**Comment by thedicemaster** [comment]
transfer over USB is not possible, as is documented here:
https://github.com/PocketSprite/8bkc-sdk/blob/master/docs/hardware/specs.rst
the usb port is only connected to the charging circuit, there's no data connection.

**Comment by classilla** [comment]
Unfortunate.
